# Generated by Django 6.0.4 on 2026-04-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='receipt_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
