# Generated by Django 6.0.4 on 2026-04-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_consultation_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='receipt_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='receipt_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
